name: news_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_web_plugins:
    sdk: flutter

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  webview_flutter: ^4.7.0
  webview_flutter_web: ^0.2.2+4
  http: ^1.2.1
  flutter_html: ^3.0.0-beta.2
  intl: ^0.19.0
  jiffy: ^6.2.2
  flutter_slidable: ^3.1.0
  shared_preferences: ^2.2.2
  share_plus: ^8.0.2
  universal_platform: ^1.0.0+1
  path_provider: ^2.1.2
  path: ^1.9.0
  html: ^0.15.4
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.4.0
  go_router: ^13.2.1
  url_launcher: ^6.2.5
  window_manager: ^0.3.8
  firebase_core: ^2.27.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  image_web: assets/splash_web.png

  android_12:
    color: "#ffffff"
    image: assets/splash.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8

flutter_launcher_icons:
  android: "ic_launcher"
  adaptive_background_color: #FF5252
  image_path: "assets/ic_launcher.png"
  web:
    generate: true
    image_path: "assets/ic_launcher.png"
  windows:
    generate: true
    image_path: "assets/ic_launcher.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:

  uses-material-design: true

  assets:
    - assets/splash.png
    - assets/splash_web.png
    - assets/images/
    - assets/demo_files/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
