name: news_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_web_plugins:
    sdk: flutter

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  webview_flutter: ^4.2.0
  webview_flutter_web: ^0.2.2+1
  http: ^0.13.6
#  flutter_html: ^2.2.1
  flutter_html: ^3.0.0-alpha.6
#  universal_html: ^2.2.1
  intl: ^0.18.1
  jiffy: ^6.1.0
  flutter_slidable: ^3.0.0
  shared_preferences: ^2.1.1
  fade_shimmer: ^2.2.0
  share_plus: ^7.0.1
  universal_platform: ^1.0.0+1
  path_provider: ^2.0.15
  path: ^1.8.3
  html: ^0.15.3
  beautiful_soup_dart: ^0.3.0
  cached_network_image: ^3.2.3
  loading_animation_widget: ^1.2.0+4
  flutter_native_splash: ^2.3.0
  go_router: ^7.0.1
  string_validator: ^1.0.0
  url_launcher: ^6.1.11
  window_manager: ^0.3.2
  universal_io: ^2.2.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  image_web: assets/splash_web.png

  android_12:
    color: "#ffffff"
    image: assets/splash.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/splash.png
    - assets/splash_web.png
    - assets/images/
    - assets/demo_files/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
