name: news_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  http: ^0.13.5
  webview_flutter: ^4.2.0
  webview_flutter_web: ^0.2.2+1
  intl: ^0.18.1
  jiffy: ^6.1.0
#  flutter_html: ^2.2.1
  flutter_slidable: ^3.0.0
  shared_preferences: ^2.1.0
  fade_shimmer: ^2.2.0
  share_plus: ^6.3.3
#  universal_platform: ^1.0.0+1
  path_provider: ^2.0.14
  path: ^1.8.2
  html: ^0.15.2
  beautiful_soup_dart: ^0.3.0
  cached_network_image: ^3.2.3
  loading_animation_widget: ^1.2.0+4
  flutter_native_splash: ^2.2.19
  go_router: ^6.5.8
  string_validator: ^1.0.0
  url_launcher: ^6.1.10

flutter_native_splash:
  color: "#ff8a80"
  image: assets/splash.png

  android_12:
    color: "#ff8a80"
    image: assets/splash.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/splash.png
    - assets/plus.png
    - assets/notfound.png
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
